// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: llm_service.proto

package llm_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmbeddingRequest for a single text input.
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// BatchEmbeddingRequest for multiple text inputs.
type BatchEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEmbeddingRequest) Reset() {
	*x = BatchEmbeddingRequest{}
	mi := &file_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEmbeddingRequest) ProtoMessage() {}

func (x *BatchEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*BatchEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchEmbeddingRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

// EmbeddingResult represents a single embedding vector.
type EmbeddingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // The actual embedding vector (e.g., 768 f32 values)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResult) Reset() {
	*x = EmbeddingResult{}
	mi := &file_llm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResult) ProtoMessage() {}

func (x *EmbeddingResult) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResult.ProtoReflect.Descriptor instead.
func (*EmbeddingResult) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddingResult) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// EmbeddingResponse contains results for a batch embedding request.
type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbeddingResult     `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"` // List of embedding results, one for each input text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_llm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{3}
}

func (x *EmbeddingResponse) GetEmbeddings() []*EmbeddingResult {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

// --- Prompt Service Definitions ---
// PromptRequest for sending a text prompt to the LLM.
type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_llm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{4}
}

func (x *PromptRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PromptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// PromptResponse contains the generated text from a prompt.
type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // The generated text response from the LLM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_llm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{5}
}

func (x *PromptResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_llm_service_proto protoreflect.FileDescriptor

const file_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x11llm_service.proto\x12\vllm_service\"&\n" +
	"\x10EmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"-\n" +
	"\x15BatchEmbeddingRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\")\n" +
	"\x0fEmbeddingResult\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"Q\n" +
	"\x11EmbeddingResponse\x12<\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x1c.llm_service.EmbeddingResultR\n" +
	"embeddings\"A\n" +
	"\rPromptRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\tsessionId\x18\x02 \x01(\tR\tsessionId\"$\n" +
	"\x0ePromptResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\xb9\x01\n" +
	"\x10EmbeddingService\x12K\n" +
	"\fGetEmbedding\x12\x1d.llm_service.EmbeddingRequest\x1a\x1c.llm_service.EmbeddingResult\x12X\n" +
	"\x12GetBatchEmbeddings\x12\".llm_service.BatchEmbeddingRequest\x1a\x1e.llm_service.EmbeddingResponse2\\\n" +
	"\rPromptService\x12K\n" +
	"\x0eGeneratePrompt\x12\x1a.llm_service.PromptRequest\x1a\x1b.llm_service.PromptResponse0\x01B\x1dZ\x1bai_orchestrator/llm_serviceb\x06proto3"

var (
	file_llm_service_proto_rawDescOnce sync.Once
	file_llm_service_proto_rawDescData []byte
)

func file_llm_service_proto_rawDescGZIP() []byte {
	file_llm_service_proto_rawDescOnce.Do(func() {
		file_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)))
	})
	return file_llm_service_proto_rawDescData
}

var file_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_llm_service_proto_goTypes = []any{
	(*EmbeddingRequest)(nil),      // 0: llm_service.EmbeddingRequest
	(*BatchEmbeddingRequest)(nil), // 1: llm_service.BatchEmbeddingRequest
	(*EmbeddingResult)(nil),       // 2: llm_service.EmbeddingResult
	(*EmbeddingResponse)(nil),     // 3: llm_service.EmbeddingResponse
	(*PromptRequest)(nil),         // 4: llm_service.PromptRequest
	(*PromptResponse)(nil),        // 5: llm_service.PromptResponse
}
var file_llm_service_proto_depIdxs = []int32{
	2, // 0: llm_service.EmbeddingResponse.embeddings:type_name -> llm_service.EmbeddingResult
	0, // 1: llm_service.EmbeddingService.GetEmbedding:input_type -> llm_service.EmbeddingRequest
	1, // 2: llm_service.EmbeddingService.GetBatchEmbeddings:input_type -> llm_service.BatchEmbeddingRequest
	4, // 3: llm_service.PromptService.GeneratePrompt:input_type -> llm_service.PromptRequest
	2, // 4: llm_service.EmbeddingService.GetEmbedding:output_type -> llm_service.EmbeddingResult
	3, // 5: llm_service.EmbeddingService.GetBatchEmbeddings:output_type -> llm_service.EmbeddingResponse
	5, // 6: llm_service.PromptService.GeneratePrompt:output_type -> llm_service.PromptResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_llm_service_proto_init() }
func file_llm_service_proto_init() {
	if File_llm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_llm_service_proto_goTypes,
		DependencyIndexes: file_llm_service_proto_depIdxs,
		MessageInfos:      file_llm_service_proto_msgTypes,
	}.Build()
	File_llm_service_proto = out.File
	file_llm_service_proto_goTypes = nil
	file_llm_service_proto_depIdxs = nil
}
